#!/bin/bash
tst="test03"
val="1000"
val2="5"
spc="5 1000"
./tp1 $val $val2 > RES1
./tp1 $val2 $val > RES2


[ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES1)" ]&& [ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2)" ]&& echo "\e[32;1m ✓ $tst\e[0m: El resultado para MCD y MCM de $val y $val2 fue $(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2)"
[ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES1)" ]|| [ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2)" ]&& echo "\e[31;1m ✗ $tst\e[0m: El resultado para MCD y MCM de $val y $val2 fue $(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2) en vez $spc"
rm RES1
rm RES2