#!/bin/bash
tst="test06"
val="3"

./tp1 -o - $val  2> RES1 >/dev/null

[ "" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con un solo numero nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el programa con un solo numero no nos dio error"
rm RES1
