#!/bin/bash
tst="test08"
val1="400000000000000000000"
val2="4"

./tp1 -o - $val1 $val2 2> RES1 >/dev/null

[ "" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con un numero fuera ed rango nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el programa con un numero fuera ed rango no nos dio error"
rm RES1
