#!/bin/bash
tst="test06"
val="3"

spc="Error en los argumentos ingresados. Consulta las ayudas con ./tp1 -h"
./tp1 -o - $val  2> RES1 



[ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con un solo numero nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el progrma con un solo numero no nos dio error, en vez de eso nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1) en vez $spc"
rm RES1
