#!/bin/bash
tst="test12"
val1="3"
val2="34"

spc="Error en los argumentos ingresados. Consulta las ayudas con ./tp1 -h"
./tp1 -o - $val1 $val2 -d -m x 2> RES1 



[ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con un caracter incorrecto extra al final nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el programa con un caracter incorrecto extra al final no nos dio error, en vez de eso nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1) en vez $spc"
rm RES1
