#!/bin/bash
tst="test01"
val="256"
val2="192"
spc="64"
res=$(./tp1 -d -o - $val $val2)
res2=$(./tp1 -d -o - $val2 $val)


[ $spc = $res ]&& [ $spc = $res2 ]&& echo "\e[32;1m ✓ $tst\e[0m: El MCD de $val y $val2 fue $res"
[ $spc != $res ]|| [ $spc != $res2 ]&& echo "\e[31;1m ✗ $tst\e[0m: El MCD de $val y $val2 fue $res en vez $spc"

#DOS NUMEROS NORMALES PARA MCD 