#!/bin/bash
tst="test10"
val1="1"
val2="4"

spc="El parámetro ingresado: (1) no es válido."
./tp1 -o - $val1 $val2 2> RES1 



[ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con 1 en vez de un numero valido nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el programa con 1 en vez de un numero valido no nos dio error, en vez de eso nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1) en vez $spc"
rm RES1
