#!/bin/bash
tst="test14"
val="10"
val2="5"
spc="5 10"
./tp1 -o RES1 $val $val2 
./tp1 -o RES2 $val2 $val 


[ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES1)" ]&& [ "$spc" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2)" ]&& echo "\e[32;1m ✓ $tst\e[0m: El resultado para MCD y MCM de $val y $val2 fue $(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2)"
[ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES1)" ]|| [ "$spc" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2)" ]&& echo "\e[31;1m ✗ $tst\e[0m: El resultado para MCD y MCM de $val y $val2 fue $(awk 'BEGIN{FS="\n"; RS = ""} { print $1,$2 }' RES2) en vez $spc"
rm RES1
rm RES2

