#!/bin/bash
tst="test10"
val1="1"
val2="4"

./tp1 -o - $val1 $val2 2> RES1 >/dev/null



[ "" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con 1 en vez de un numero valido nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el programa con 1 en vez de un numero valido no nos dio error"
rm RES1
