#!/bin/bash
tst="test05"
val1="7"
val2="13"
val3="23"

./tp1 -o - $val1 $val2 $val3 2>RES1 >/dev/null 

[ "" != "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[32;1m ✓ $tst\e[0m: Al ejecutar el programa con un numero de mas nos dio: $(awk 'BEGIN{FS="\n"; RS = ""} { print $0 }' RES1)"
[ "" = "$(awk 'BEGIN{FS="\n"; RS = ""} { print $1 }' RES1)" ]&& echo "\e[31;1m ✗ $tst\e[0m: Al ejecutar el programa con un numero de mas nos dio error"
rm RES1
