FLAGS = -Wall -Werror -Wconversion -std=c99  -g -O0

#test:
#	gcc $(FLAGS) decode_encode.h decode_encode.c TP0_test.c -o pruebas

#	./pruebas
tp1:
	gcc $(FLAGS) TP1.c mcm.S mcd.S -o tp1

tp1l:
	gcc $(FLAGS) TP1.c -o tp1
