#!/bin/bash
tst="test03"
wrd="TWFu"
spc="Man"
res=$(echo -n $wrd | ./TP0 -d)

[ $spc = $res ]&& echo "\e[32;1m ✓ $tst\e[0m: Decodificar palabra. $wrd \n\t Decodificación: $res"
[ $spc != $res ]&& echo "\e[31;1m ✗ $tst\e[0m: Decodificar palabra. $wrd \n\t Decodificación: $res"